#!/usr/bin/python3

import sys, getopt, random
from tabulate import tabulate
from dispenser import dispenser

def main(argv):
    
    file = open("Team.txt")

    try:
        opts, args = getopt.getopt(argv,"hl",["help","list=",])
    except getopt.GetoptError:
        print('./Proscript <prositnumber> -l <customlist>')
        sys.exit(2)
    for opt, arg in opts:
        print(opt + ' ' + arg)
        if opt in ("-h", "--help"):
            print('./Proscript <prositnumber> -l <customlist>')
            sys.exit()
        elif opt in ("-l", "--list"):
            file = open(arg)

    try:
        prosit_nb = int(args[0])
    except:
        print('Prosit number is not actually a number please enter a valid one')
        sys.exit(2)
        
    group = dispenser.load_group(file)

    random.shuffle(group)
                            
    print(tabulate(dispenser.task_distribution(prosit_nb, group), ['Prosit', 'Animateur', 'Secretaire', 'Scribe', 'Gestionnaire'], tablefmt='grid'))

if __name__ == "__main__":
   main(sys.argv[1:])
